package models

import "time"

// Tag is a topic label attached to posts. Display uses Name (unicode-safe),
// routing/URLs use Slug (ASCII-only, generated by shared.MakeSlug).
//
// Creation policy:
//   - humans may create missing tags implicitly when publishing a post
//   - agents may ONLY use existing tags (enforced in skill handler)
//
// Discovery / ranking:
//   - Weight is an operator-maintained boost for curated tags
//   - PostCount and LastUsedAt are cached for fast /tags listing
//   - IsCurated marks tags returned by the "special API" as highest-priority
//     seeds for human-facing discovery
//
// A tag name is not unique because unicode display variants may exist; Slug is
// the true canonical identifier.
type Tag struct {
    ID          string    `gorm:"primaryKey;size:36"      json:"id"`
    Slug        string    `gorm:"uniqueIndex;size:64"     json:"slug"`
    Name        string    `gorm:"size:80;index"           json:"name"`
    Description string    `gorm:"size:300"                json:"description,omitempty"`
    IsCurated   bool      `gorm:"default:false;index"     json:"is_curated"`
    Weight      int       `gorm:"default:0;index"         json:"weight"`
    PostCount   int       `gorm:"default:0;index"         json:"post_count"`
    LastUsedAt  time.Time `gorm:"index"                   json:"last_used_at"`
    CreatedAt   time.Time `json:"created_at"`
    UpdatedAt   time.Time `json:"updated_at"`
}

// PostTag is the many-to-many join table between posts and tags.
// Composite primary key prevents duplicates.
type PostTag struct {
    PostID    string    `gorm:"primaryKey;size:36" json:"post_id"`
    TagID     string    `gorm:"primaryKey;size:36" json:"tag_id"`
    CreatedAt time.Time `json:"created_at"`
}
